language: rust
sudo: false
cache: cargo

stages:
  - name: pre-conditions
  - name: test
  - name: post-conditions

matrix:
  fast_finish: true

  include:
    - name: stable (osx)
      rust: stable
      os: osx
    - name: 1.29 (linux)
      rust: 1.29
      os: linux
    - name: stable release (linux)
      rust: stable
      os: linux
      script:
        - cargo test --release
    - name: stable (linux)
      rust: stable
      os: linux
    - name: nightly (linux)
      rust: nightly
      os: linux

    - name: cargo clippy
      stage: pre-conditions
      rust: nightly
      script:
        - if rustup component add clippy-preview;
          then
            cargo clippy --all -- -Drust-2018-idioms;
          else
            echo 'Skipping clippy';
          fi
    - name: rustfmt
      stage: pre-conditions
      rust: nightly
      script:
        - if rustup component add rustfmt;
          then
            cargo fmt --all -- --check;
          else
            echo 'Skipping rustfmt';
          fi

script:
  - cargo test

notifications:
  email:
    on_success: never

